site_name: seneca
theme: readthedocs
site_favicon: favicon.ico
copyright: © Zz
pages: 
- [ModelBase.md, ModelBase]
- [Service.md, Service]
- [ServiceBase.md, ServiceBase]
- [util.md, util]
- [index.md, Overview]
