site_name: seneca
theme: readthedocs
site_favicon: favicon.ico
copyright: © Zz
pages: 
- [util.md, util]
- [Service.md, Service]
- [ServiceBase.md, ServiceBase]
- [ServiceUtilBase.md, ServiceUtilBase]
- [index.md, Overview]
