site_name: seneca
theme: readthedocs
site_favicon: favicon.ico
copyright: © Zz
pages: 
- [index.md, Overview]
- [FCClient.md, FCClient]
- [FCService.md, FCService]
- [ModelBase.md, ModelBase]
- [ServiceBase.md, ServiceBase]
- [ServiceImp.md, ServiceImp]
- [util.md, util]
- [XmlUtil.md, XmlUtil]
